### ISSUE TITLE
Docs not in line with latest package

### ISSUE THREAD

**Issue by Dyllaann** [raymondbutcher/pretf#51]
Heyo,

I just started playing around with pretf, as you suggested [here](https://github.com/claranet/jinjaform/issues/28). Though, I tried the flatten example, but the latest pip package does not yet contain the `delete_links` method in the workflow.py.
```python
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pretf import workflow
>>> workflow.delete_links()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pretf.workflow' has no attribute 'delete_links' 
```

The latest release of the pip package seems to be September'19. Is that correct @raymondbutcher?

**Comment by raymondbutcher** [comment]
Hi @Dyllaann. Thanks for trying it out. On the docs site you can change the version from latest to stable and it should match the version on pip. In github you can view the latest tag for the examples to match up with the docs and pip.

And yep, there hasn’t been a pip release for a while. The current version works well and I’m taking my time with new ideas/features to hopefully get them right.
