### ISSUE TITLE
Add 'configparser' to package's deps

### ISSUE THREAD

**Issue by pepoluan** [raymondbutcher/pretf#57]
On a fresh virtualenv, `pretf plan` fails with `ModuleNotFoundError: No module named 'configparser'`

The solution is to `pip install configparser` before running `pretf plan`.

I think the dependencies of the package needs to be updated.

**Comment by raymondbutcher** [comment]
Hi @pepoluan. What version of Python are you using? It should be included in the standard library for any supported version of  Python (3.6 and above) as far as I know.

**Comment by pepoluan** [comment]
Hi @raymondbutcher , I was running pretf under a CPython 3.6 virtualenv (on Ubuntu 18.04 WSL).

I _did_ use a "minimal Ubuntu image" to create the WSL environment, manually "unminimized" on my own, so the "usual" packages might be missing.

**Comment by raymondbutcher** [comment]
I think this was a problem with your Python installation as I've not encountered this issue across multiple machines and operating systems. Please reopen if you disagree.
