### ISSUE TITLE
Flattening inside of pretf block resource

### ISSUE THREAD

**Issue by sergekh42** [raymondbutcher/pretf#64]
Hi I just rewrote all my terraform to use pretf and hit this final snag that is blocking me.
I am using it for the Vsphere VMware provider.

I am creating 2 network interfaces and they are the same key. So when looking in the JSON, there is only Storage Network. Because it flattened them and therefore only the 2nd one is kept. How can I stop these from being flattened?

Pretf python code
```
yield block("resource", "vsphere_virtual_machine", server['resource_name'], {
            "network_interface": {
                "network_id": host_network.id,
            },
            "network_interface": {
                "network_id": storage_network.id,
            },
```

The old terraform code
```
resource vsphere_virtual_machine "vm" {
  network_interface {
    network_id   = data.vsphere_network.host_network.id
    }
  network_interface {
    network_id   = data.vsphere_network.storage_network.id
    }
```

The JSON output made by pretf
```
"resource": {
      "vsphere_virtual_machine": {
        "vm": {
          #### There should be another network_interface on this line ####
           "network_interface": {
            "network_id": "${data.vsphere_network.storage_network.id}"
          },
```

**Comment by raymondbutcher** [comment]
Hi @sergekh42, does the following work?

```
yield block("resource", "vsphere_virtual_machine", server['resource_name'], {
    "network_interface": [
        {"network_id": host_network.id},
        {"network_id": storage_network.id},
    ],
    ...
})
```

This is not specific to Pretf, it's about how Terraform expects multiple nested block mappings in JSON format. There is an explanation [https://www.terraform.io/docs/language/syntax/json.html#nested-block-mapping](here) but, in short, just make it a list of dictionaries when there are multiple blocks with the same name.

**Comment by raymondbutcher** [comment]
Closing this since I don't think there's anything to do. Feel free to reopen!
